"use client"

import { Geist, Geist_Mono, Inter } from "next/font/google"

import "gorth-ui/globals.css";
import { ThemeProvider } from "gorth-ui/providers/theme";
import { ToasterProvider } from "gorth-ui/providers/toaster";
import { TooltipProvider } from "gorth-ui/default/tooltip";
import { AuthProvider } from "@/providers/auth";
import { cn } from "gorth-ui/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'})

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("antialiased", fontMono.variable, "font-sans", inter.variable)}
    >
    <body>
      <ThemeProvider>
        <TooltipProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
          <ToasterProvider/>
        </TooltipProvider>
      </ThemeProvider>
    </body>
    </html>
  )
}

// import { Geist, Geist_Mono } from "next/font/google";
// import "gorth-ui/globals.css";
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <body>{children}</body>
//     </html>
//   );
// }
