"use client"

import { useEffect } from "react";
import { Geist_Mono, Inter } from "next/font/google"

import "@/styles/globals.css"
import "@gorth/primitive/globals.css";
import { ThemeProvider } from "@gorth/primitive/providers/theme";
import { ToasterProvider } from "@gorth/primitive/providers/toaster";
import { TooltipProvider } from "@gorth/primitive/default/tooltip";
import { AuthProvider } from "@/providers/auth";
import { cn } from "@gorth/primitive/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'})

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "antialiased",
        // "overflow-auto scrollbar-none scrollbar-thumb-gray-400 scrollbar-track-transparent",
        fontMono.variable,
        "font-sans",
        inter.variable
      )}
    >
    <body>
      <ThemeProvider>
        <TooltipProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
          <ToasterProvider/>
        </TooltipProvider>
      </ThemeProvider>
    </body>
    </html>
  )
}

// import { Geist, Geist_Mono } from "next/font/google";
// import "@gorth/primitive/globals.css";
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <body>{children}</body>
//     </html>
//   );
// }
